name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
    steps:
      - name: Install Git
        run: apk add --no-cache git

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build script
        run: sh build.sh

      - name: Add CNAME for custom domain
        run: echo "recipe.zawie.io" > ./html/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
